BRAINSTEMS_TOKEN_NAME = "Brainstems Token";
BRAINSTEMS_TOKEN_SYMBOL = "STEMS";
BRAINSTEMS_TOKEN_EVENTS = {
  TOKENS_DISTRIBUTED: "TokensDistributed"
};
BRAINSTEMS_TOKEN_MAX_SUPPLY = BigInt(100e6) * BigInt(1e18);
BRAINSTEMS_TOKEN_DECIMALS = 18;

module.exports = {
  BRAINSTEMS_TOKEN_NAME,
  BRAINSTEMS_TOKEN_SYMBOL,
  BRAINSTEMS_TOKEN_EVENTS,
  BRAINSTEMS_TOKEN_MAX_SUPPLY,
  BRAINSTEMS_TOKEN_DECIMALS
};
