INTELLTOKEN_NAME = "Intelligence Token";
INTELLTOKEN_SYMBOL = "INTELL";
INTELLTOKEN_STAGES = {
  WHITELISTING: 0n,
  PRIVATE_SALE: 1n,
  PUBLIC_SALE: 2n,
  FINISHED: 3n,
};
INTELLTOKEN_EVENTS = {
  RATE_UPDATED: "RateUpdated",
  TOKENS_PURCHASED: "TokensPurchased",
};
INTELLTOKEN_MAX_SUPPLY = BigInt(1000e6) * BigInt(1e18);
INTELLTOKEN_INVESTORS_CAP = BigInt(100e6) * BigInt(1e18);
INTELLTOKEN_SALES_CAP = BigInt(70e6) * BigInt(1e18);
INTELLTOKEN_TO_USDC = 10n;
USDCOIN_NAME = "USD Coin";
USDCOIN_SYMBOL = "USDC";
USDCOIN_DECIMALS = 6;

module.exports = {
  INTELLTOKEN_NAME,
  INTELLTOKEN_SYMBOL,
  INTELLTOKEN_STAGES,
  INTELLTOKEN_EVENTS,
  INTELLTOKEN_MAX_SUPPLY,
  INTELLTOKEN_INVESTORS_CAP,
  INTELLTOKEN_SALES_CAP,
  INTELLTOKEN_TO_USDC,
  USDCOIN_NAME,
  USDCOIN_SYMBOL,
  USDCOIN_DECIMALS,
};
