INTELLTOKEN_NAME = "Intelligence Token";
INTELLTOKEN_SYMBOL = "INTELL";
INTELLTOKEN_STAGES = {
  WHITELISTING: 0n,
  PRIVATE_SALE: 1n,
  PUBLIC_SALE: 2n,
  FINISHED: 3n,
};
INTELLTOKEN_EVENTS = {
  RATE_UPDATED: "RateUpdated",
};

module.exports = {
  INTELLTOKEN_NAME,
  INTELLTOKEN_SYMBOL,
  INTELLTOKEN_STAGES,
  INTELLTOKEN_EVENTS,
};
