module.exports = {
    recipient: "xxxxx",
    truthHolder: "xzzzz",
    paymentToken: "xxx",
    admin: "kkkk",
    tiex_share_collection_name: "TIEx Share Collections",
    tiex_share_collection_symbol: "TIExSHARE",
    truthHolder: "xxxx",
    admin: "xxxx",
    intell_token: "xxxx",
    creator_rate: 2000,
    marketing_rate: 2000,
    presale_rate: 1000,
    reserve_rate: 5000,
    marketing_address: "xxxx",
    presale_address: "xxxxx",
    reserve_address: "xxxxx",
    proxy: "xxxxx",
    model_001: {
        model_id: 1,
        creator: "xxxxx",
        ipfsHash: "xxxxx",
        contributors: []
    },
}